

spring:
  h2.console:
    enabled: true
    path: /h2
    settings:
      trace: false
      web-allow-others: true
  
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    prefix: classpath:templates/
    suffix: .html
  
  devtools.livereload.enabled: true
  
  data.rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 881218558153-ndr868i68rlofoo4l2gb488ksabi5q23.apps.googleusercontent.com
            client-secret: kq6zIo0myJotHK5_0irhtYnW
          facebook:
            client-id: 465358593799840
            client-secret: a37286e3dae00dcdce628f40dfe363f5
custom:
  oauth2:
    kakao:
      client-id: 1b8ff676ae01724ed77437f98d399543


env:
  test:
    servers:
    - dev.tain.org
    - test.tain.org
    - real.tain.org
    - tain.org
    user:
      name: kiea
      size: 100
      content: Hello, world!!!
#  data-json-file: classpath:1000-2.json
  data-json-file: src/main/resources/1000-2.json

##############################################################
spring.profiles.active: local-http

---
spring:
  profiles: local-http
  
server.port: 8080

---
spring:
  profiles: local-https
  
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:serverkeystore.p12
    key-store-type: PKCS12
    key-store-password: server
    key-alias: serverkey



