


#
# server:
#   port: 8443
#   ssl:
#     key-alias: https-example
#     key-store-type: JKS
#     key-password: password
#     key-store: classpath:https-example.jks

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:serverkeystore.p12
    key-store-password: server
    key-alias: serverkey
    key-store-type: PKCS12







